# Generated by Django 2.2.5 on 2019-11-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thongtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Giaovien', models.CharField(max_length=100)),
                ('MSSV', models.CharField(max_length=100)),
                ('Trangthai', models.CharField(max_length=100)),
                ('Ghichu', models.CharField(max_length=100)),
            ],
        ),
    ]
