# Generated by Django 2.2.5 on 2019-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0004_auto_20191105_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='File',
            field=models.ImageField(null=True, upload_to='Taokhoa/'),
        ),
    ]
