# Generated by Django 2.2.5 on 2019-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0005_auto_20191106_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='taokhoa',
            name='MSCB',
            field=models.FloatField(null=True),
        ),
    ]
