# Generated by Django 2.2.5 on 2019-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0007_auto_20191106_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='MSCB',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
