# Generated by Django 2.2.5 on 2019-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0008_list_mscb'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='MSCB',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='thongtin',
            name='MSCB',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='xac',
            name='MSCB',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
