# Generated by Django 2.2.5 on 2019-11-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0009_auto_20191106_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='UserRegis',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
