# Generated by Django 2.2.5 on 2019-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0010_list_userregis'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtin',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
